In [1]:
import pandas as pd
import json

In [2]:
with open("chessbuds_messages.json") as j:
    spot = json.load(j)

In [3]:
type(spot)

dict

In [4]:
spot.keys()

dict_keys(['participants', 'messages', 'title', 'is_still_participant', 'thread_type', 'thread_path', 'magic_words', 'joinable_mode'])

In [5]:
type(spot['participants'])

list

In [6]:
type(spot['messages'])

list

In [7]:
type(spot['title'])

str

In [8]:
type(spot['is_still_participant'])

bool

In [9]:
type(spot['thread_type'])

str

In [10]:
type(spot['thread_path'])

str

In [11]:
type(spot['magic_words'])

list

In [12]:
type(spot['joinable_mode'])

dict

In [13]:
spot['joinable_mode'].keys()

dict_keys(['mode', 'link'])

In [14]:
type(spot['joinable_mode']['mode'])

int

In [15]:
type(spot['joinable_mode']['link'])

str

In [16]:
chessbuds = pd.DataFrame(spot['messages'])
chessbuds.head()

,sender_name,timestamp_ms,content,reactions,type,is_unsent,is_taken_down,bumped_message_metadata,share,photos,gifs,users
0,Joanna Rusch,1666374933946,Maybe he just wants to ride the publicity for ...,"[{'reaction': 'ð', 'actor': 'Chad Larson'},...",Generic,False,False,{'bumped_message': 'Maybe he just wants to rid...,NaN,NaN,NaN,NaN
1,Chad Larson,1666373448613,To be fair to Hans....no one wants to be assoc...,"[{'reaction': 'ð', 'actor': 'Scott Pence'},...",Generic,False,False,{'bumped_message': 'To be fair to Hans....no o...,NaN,NaN,NaN,NaN
2,Chad Larson,1666373216381,He would have to prove he didn't cheat and tha...,"[{'reaction': 'ð', 'actor': 'Scott Pence'},...",Generic,False,False,{'bumped_message': 'He would have to prove he ...,NaN,NaN,NaN,NaN
3,Scott Pence,1666373164883,"Yeah, no way. You over shoot and hope to get a...","[{'reaction': 'ð', 'actor': 'Chad Larson'},...",Generic,False,False,"{'bumped_message': 'Yeah, no way. You over sho...",NaN,NaN,NaN,NaN
4,Chad Larson,1666373111157,"From what I see, I don't think he could win. ...",NaN,Generic,False,False,"{'bumped_message': 'From what I see, I don't t...",NaN,NaN,NaN,NaN

In [ ]:
cb = pd.DataFrame(spot['messages'])
cb['timestamp_ms'] = pd.to_datetime(cb['timestamp_ms'], unit='ms')
cb.head()

,sender_name,timestamp_ms,content,reactions,type,is_unsent,is_taken_down,bumped_message_metadata,share,photos,gifs,users
0,Joanna Rusch,2022-10-21 17:55:33.946,Maybe he just wants to ride the publicity for ...,"[{'reaction': 'ð', 'actor': 'Chad Larson'},...",Generic,False,False,{'bumped_message': 'Maybe he just wants to rid...,NaN,NaN,NaN,NaN
1,Chad Larson,2022-10-21 17:30:48.613,To be fair to Hans....no one wants to be assoc...,"[{'reaction': 'ð', 'actor': 'Scott Pence'},...",Generic,False,False,{'bumped_message': 'To be fair to Hans....no o...,NaN,NaN,NaN,NaN
2,Chad Larson,2022-10-21 17:26:56.381,He would have to prove he didn't cheat and tha...,"[{'reaction': 'ð', 'actor': 'Scott Pence'},...",Generic,False,False,{'bumped_message': 'He would have to prove he ...,NaN,NaN,NaN,NaN
3,Scott Pence,2022-10-21 17:26:04.883,"Yeah, no way. You over shoot and hope to get a...","[{'reaction': 'ð', 'actor': 'Chad Larson'},...",Generic,False,False,"{'bumped_message': 'Yeah, no way. You over sho...",NaN,NaN,NaN,NaN
4,Chad Larson,2022-10-21 17:25:11.157,"From what I see, I don't think he could win. ...",NaN,Generic,False,False,"{'bumped_message': 'From what I see, I don't t...",NaN,NaN,NaN,NaN

In [18]:
formatted_cb = pd.melt(cb,['sender_name'])
formatted_cb = formatted_cb.sort_values(by=['sender_name'])
cb.head()

,sender_name,timestamp_ms,content,reactions,type,is_unsent,is_taken_down,bumped_message_metadata,share,photos,gifs,users
0,Joanna Rusch,2022-10-21 17:55:33.946,Maybe he just wants to ride the publicity for ...,"[{'reaction': 'ð', 'actor': 'Chad Larson'},...",Generic,False,False,{'bumped_message': 'Maybe he just wants to rid...,NaN,NaN,NaN,NaN
1,Chad Larson,2022-10-21 17:30:48.613,To be fair to Hans....no one wants to be assoc...,"[{'reaction': 'ð', 'actor': 'Scott Pence'},...",Generic,False,False,{'bumped_message': 'To be fair to Hans....no o...,NaN,NaN,NaN,NaN
2,Chad Larson,2022-10-21 17:26:56.381,He would have to prove he didn't cheat and tha...,"[{'reaction': 'ð', 'actor': 'Scott Pence'},...",Generic,False,False,{'bumped_message': 'He would have to prove he ...,NaN,NaN,NaN,NaN
3,Scott Pence,2022-10-21 17:26:04.883,"Yeah, no way. You over shoot and hope to get a...","[{'reaction': 'ð', 'actor': 'Chad Larson'},...",Generic,False,False,"{'bumped_message': 'Yeah, no way. You over sho...",NaN,NaN,NaN,NaN
4,Chad Larson,2022-10-21 17:25:11.157,"From what I see, I don't think he could win. ...",NaN,Generic,False,False,"{'bumped_message': 'From what I see, I don't t...",NaN,NaN,NaN,NaN

In [19]:
chessbuds2 = pd.DataFrame(spot['participants'])
chessbuds2.head()

                   name
0           Scott Pence
1           Chad Larson
2          Joanna Rusch
3  Angela Babbitt Pence
4           David Silva

In [20]:
spot['title']

'Chess Buds'

In [21]:
spot['is_still_participant']

True

In [22]:
spot['thread_type']

'RegularGroup'

In [23]:
spot['thread_path']

'inbox/chessbuds_npjakt9u1g'

In [24]:
spot['magic_words']

[]

In [25]:
spot['joinable_mode']['link']

''

In [26]:
spot['joinable_mode']['mode']

1

Note: I give up on things like this super easy. Mostly because I run into issues with mental energy to figure it out.

I recognize it for what it is. Messages is where the important data is. How to tidy it up, because it's a list is what I struggled with. I have ChatGPT and, believe me, I was tempted to use it - not to copy/paste - but to gain a greater understanding of what I'm missing. There's a way to break the data out of a simple list - as I'm reading Hould's piece. 

But I would use it to determine activity in the group chat. Or unsent messages. Or reaction usage. But most of the data here is completely frivolous and any form of dissemination, beyond activity, is purely useless and any data scientist who tries to break anything other than activity is simply wasting their time. 

There is one circumstance - in Content - searching for a specific string within that string would be useful, or knowing how many messages were "bumped." In a way... knowing the time gap between messages would also be beneficial. But surely there are easier ways of doing these things... and again. I stand by my sentiment. There are elements of this data that serve no purpose whatsoever.