In [59]:
import pandas as pd

In [60]:
data_dict = {'VK': [76,71,69], 'PB': [71,72,74], 'LT': [73,70,75]}
dat = pd.DataFrame(data_dict)

dat

   VK  PB  LT
0  76  71  73
1  71  72  70
2  69  74  75

In [61]:
dat.head(1)

   VK  PB  LT
0  76  71  73

In [62]:
dat.tail(1)

   VK  PB  LT
2  69  74  75

In [63]:
dat['VK']

0    76
1    71
2    69
Name: VK, dtype: int64

In [64]:
dat.loc[0]

VK    76
PB    71
LT    73
Name: 0, dtype: int64

In [65]:
list = pd.DataFrame (
    {
        "VK": pd.Series([76,71,69]),
        "PB": pd.Series([71,72,74]),
        "LT": pd.Series([73,70,75]),
    }
)

list

   VK  PB  LT
0  76  71  73
1  71  72  70
2  69  74  75

In [66]:
dat.to_csv("pandas.csv")

# Murray Chapter 1

### What does the "write/render/evaluate" loop provide for creators of interactive data visualizations?

Just like what I do for graphic design, it provides us with alternative mappings, and seeing output instaneously.

### Why are dynamic, interactive data visualizations useful when communicating data?

Encourages users to explore the data at their own pace and with their own intentions.
    
### Do you agree with Murray's claim that open-source tools that avoid proprietary software are best for publishing data visualization? In a few sentences, explain why you do or do not agree.

I agree. Proprietary stuff gets retired on occasion... finances become unavailable... there's a multitude of factors that play into proprietary stuff becoming inaccessible. I have a fear of open-source for specific reasons, but in the end... open source is dangerous, but proprietary is more dangerous.